# Generated by Django 3.2.25 on 2024-09-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=255)),
                ('agent', models.CharField(choices=[('AGODA', 'Agoda'), ('EXPEDIA', 'Expedia'), ('TRIP_DOT_COM', 'Trip.com')], max_length=255)),
                ('reservation_name', models.CharField(max_length=255)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('staying_number', models.IntegerField(default=1)),
                ('room_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('CANCEL', 'Cancel')], max_length=255)),
                ('amount', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Event',
            },
        ),
    ]
