# Generated by Django 3.2.25 on 2024-09-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='room_name',
            field=models.CharField(choices=[('NAGASAKI', '長崎'), ('FUKUOKA', '福岡'), ('KUMAMOTO', '熊本')], max_length=255),
        ),
    ]
