# Generated by Django 3.2.25 on 2024-09-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_auto_20240918_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gender',
            field=models.CharField(choices=[('MAN', '남'), ('WOMAN', '여')], default='MAN', max_length=255),
        ),
    ]
